### ISSUE TITLE
support non-ASCII characters in usernames

### ISSUE THREAD

**Issue by salim-b** [larsks/gitdriver#10]
If I try to run gitdriver, it fails with the following error:
```
Traceback (most recent call last):
  File "gitdrive.py", line 114, in <module>
    main()
  File "gitdrive.py", line 112, in main
    commit_revision(gd, opts, rev)
  File "gitdrive.py", line 68, in commit_revision
    rev['lastModifyingUserName'])], env=env)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 8: ordinal not in range(128)
```

If I'm understanding it right, this is because my Google username (`lastModifyingUserName`) includes the character `ü`. Would be nice if non-ASCII characters could be supported.

**Comment by larsks** [comment]
Thanks for the report! While I probably won't be able to get to this anytime soon, I am happy to accept pull requests.
